/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupabaseRouteImport } from './routes/supabase'
import { Route as IndexRouteImport } from './routes/index'

const SupabaseRoute = SupabaseRouteImport.update({
  id: '/supabase',
  path: '/supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/supabase': typeof SupabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/supabase'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/supabase'
  id: '__root__' | '/' | '/supabase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SupabaseRoute: typeof SupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supabase': {
      id: '/supabase'
      path: '/supabase'
      fullPath: '/supabase'
      preLoaderRoute: typeof SupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SupabaseRoute: SupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
